name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: firebase/firebase-action@v1
      with:
        credentials_file: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAREAFIREBASE }}'
        project_id: tu-proyecto-id
